name: amongUs

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Correr o Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        run: python bot.py
